---
version: 1.0.0
name: Jamie Smith • Gadget-Loving father of girls
description: Transform your plain text into static websites and blogs
url: http://grandelatte.com
repository: https://github.com/jamiesmith/jamiesmith
timezone: America/New_York
twitter:
  username: jamiesmithnc
logo: "/img/logo-2x.png"
# google_analytics_id: UA-50755011-1
# google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY
excerpt_separator: "<!--more-->"
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  links:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/blog/:year/:month/:day/:title/"
    output: true
defaults:
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
- scope:
    path: _links
    type: links
  values:
    layout: links
- scope:
    path: _posts
    type: posts
  values:
    layout: blog_item
    image: "/img/twitter-card.png"
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

sass:
  style: compressed
exclude:
- ".gitignore"
- CNAME
- icomoon-selection.json
- readme.md
remote_theme: jamiesmith/jekyllstheme

